//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Slalom.CustomAppDev.RecruitingManager.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RecruitingManagerModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RecruitingManagerModelContainer object using the connection string found in the 'RecruitingManagerModelContainer' section of the application configuration file.
        /// </summary>
        public RecruitingManagerModelContainer() : base("name=RecruitingManagerModelContainer", "RecruitingManagerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecruitingManagerModelContainer object.
        /// </summary>
        public RecruitingManagerModelContainer(string connectionString) : base(connectionString, "RecruitingManagerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecruitingManagerModelContainer object.
        /// </summary>
        public RecruitingManagerModelContainer(EntityConnection connection) : base(connection, "RecruitingManagerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Competency> Competencies
        {
            get
            {
                if ((_Competencies == null))
                {
                    _Competencies = base.CreateObjectSet<Competency>("Competencies");
                }
                return _Competencies;
            }
        }
        private ObjectSet<Competency> _Competencies;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Competencies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompetencies(Competency competency)
        {
            base.AddObject("Competencies", competency);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RecruitingManagerModel", Name="Competency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Competency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Competency object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Competency CreateCompetency(global::System.Int32 id)
        {
            Competency competency = new Competency();
            competency.Id = id;
            return competency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
    }

    #endregion

    
}
