//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Candidate", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Candidate), "CandidateFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CandidateFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Candidate", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Candidate), "CompetencyFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CompetencyFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Candidate", "Candidate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Candidate), "InterviewSession", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.InterviewSession), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CandidateFeedback), "CandidateFeedback1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CandidateFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Interviewer", "Interviewer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Interviewer), "CandidateFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CandidateFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Competency", "Competency", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Competency), "CompetencyFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CompetencyFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Interviewer", "Interviewer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Interviewer), "CompetencyFeedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.CompetencyFeedback), true)]
[assembly: EdmRelationshipAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Interviewer", "Interviewer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Slalom.CustomAppDev.RecruitingManager.Data.Interviewer), "InterviewSession", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Slalom.CustomAppDev.RecruitingManager.Data.InterviewSession), true)]

#endregion

namespace Slalom.CustomAppDev.RecruitingManager.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RecruitingManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RecruitingManagerEntities object using the connection string found in the 'RecruitingManagerEntities' section of the application configuration file.
        /// </summary>
        public RecruitingManagerEntities() : base("name=RecruitingManagerEntities", "RecruitingManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecruitingManagerEntities object.
        /// </summary>
        public RecruitingManagerEntities(string connectionString) : base(connectionString, "RecruitingManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RecruitingManagerEntities object.
        /// </summary>
        public RecruitingManagerEntities(EntityConnection connection) : base(connection, "RecruitingManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidate>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidate> _Candidates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CandidateFeedback> CandidateFeedbacks
        {
            get
            {
                if ((_CandidateFeedbacks == null))
                {
                    _CandidateFeedbacks = base.CreateObjectSet<CandidateFeedback>("CandidateFeedbacks");
                }
                return _CandidateFeedbacks;
            }
        }
        private ObjectSet<CandidateFeedback> _CandidateFeedbacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Competency> Competencies
        {
            get
            {
                if ((_Competencies == null))
                {
                    _Competencies = base.CreateObjectSet<Competency>("Competencies");
                }
                return _Competencies;
            }
        }
        private ObjectSet<Competency> _Competencies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompetencyFeedback> CompetencyFeedbacks
        {
            get
            {
                if ((_CompetencyFeedbacks == null))
                {
                    _CompetencyFeedbacks = base.CreateObjectSet<CompetencyFeedback>("CompetencyFeedbacks");
                }
                return _CompetencyFeedbacks;
            }
        }
        private ObjectSet<CompetencyFeedback> _CompetencyFeedbacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Interviewer> Interviewers
        {
            get
            {
                if ((_Interviewers == null))
                {
                    _Interviewers = base.CreateObjectSet<Interviewer>("Interviewers");
                }
                return _Interviewers;
            }
        }
        private ObjectSet<Interviewer> _Interviewers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InterviewSession> InterviewSessions
        {
            get
            {
                if ((_InterviewSessions == null))
                {
                    _InterviewSessions = base.CreateObjectSet<InterviewSession>("InterviewSessions");
                }
                return _InterviewSessions;
            }
        }
        private ObjectSet<InterviewSession> _InterviewSessions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidate candidate)
        {
            base.AddObject("Candidates", candidate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CandidateFeedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidateFeedbacks(CandidateFeedback candidateFeedback)
        {
            base.AddObject("CandidateFeedbacks", candidateFeedback);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Competencies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompetencies(Competency competency)
        {
            base.AddObject("Competencies", competency);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompetencyFeedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompetencyFeedbacks(CompetencyFeedback competencyFeedback)
        {
            base.AddObject("CompetencyFeedbacks", competencyFeedback);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Interviewers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInterviewers(Interviewer interviewer)
        {
            base.AddObject("Interviewers", interviewer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InterviewSessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInterviewSessions(InterviewSession interviewSession)
        {
            base.AddObject("InterviewSessions", interviewSession);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="Candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Candidate CreateCandidate(global::System.Int32 id)
        {
            Candidate candidate = new Candidate();
            candidate.Id = id;
            return candidate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResumeAddress
        {
            get
            {
                return _ResumeAddress;
            }
            set
            {
                OnResumeAddressChanging(value);
                ReportPropertyChanging("ResumeAddress");
                _ResumeAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResumeAddress");
                OnResumeAddressChanged();
            }
        }
        private global::System.String _ResumeAddress;
        partial void OnResumeAddressChanging(global::System.String value);
        partial void OnResumeAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> InterviewComplete
        {
            get
            {
                return _InterviewComplete;
            }
            set
            {
                OnInterviewCompleteChanging(value);
                ReportPropertyChanging("InterviewComplete");
                _InterviewComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterviewComplete");
                OnInterviewCompleteChanged();
            }
        }
        private Nullable<global::System.Boolean> _InterviewComplete;
        partial void OnInterviewCompleteChanging(Nullable<global::System.Boolean> value);
        partial void OnInterviewCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HireCandidate
        {
            get
            {
                return _HireCandidate;
            }
            set
            {
                OnHireCandidateChanging(value);
                ReportPropertyChanging("HireCandidate");
                _HireCandidate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HireCandidate");
                OnHireCandidateChanged();
            }
        }
        private Nullable<global::System.Boolean> _HireCandidate;
        partial void OnHireCandidateChanging(Nullable<global::System.Boolean> value);
        partial void OnHireCandidateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Candidate", "CandidateFeedback")]
        public CandidateFeedback CandidateFeedback
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "CandidateFeedback").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "CandidateFeedback").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CandidateFeedback> CandidateFeedbackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "CandidateFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "CandidateFeedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Candidate", "CompetencyFeedback")]
        public EntityCollection<CompetencyFeedback> CompetencyFeedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "CompetencyFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "CompetencyFeedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Candidate", "InterviewSession")]
        public EntityCollection<InterviewSession> InterviewSessions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InterviewSession>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "InterviewSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InterviewSession>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "InterviewSession", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="CandidateFeedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CandidateFeedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CandidateFeedback object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="candidateId">Initial value of the CandidateId property.</param>
        /// <param name="specialization">Initial value of the Specialization property.</param>
        /// <param name="suggestedConsultingRole">Initial value of the SuggestedConsultingRole property.</param>
        /// <param name="suggestedExperienceLevel">Initial value of the SuggestedExperienceLevel property.</param>
        /// <param name="hire">Initial value of the Hire property.</param>
        public static CandidateFeedback CreateCandidateFeedback(global::System.Int32 id, global::System.Int32 candidateId, global::System.Int32 specialization, global::System.Int32 suggestedConsultingRole, global::System.Int32 suggestedExperienceLevel, global::System.Boolean hire)
        {
            CandidateFeedback candidateFeedback = new CandidateFeedback();
            candidateFeedback.Id = id;
            candidateFeedback.CandidateId = candidateId;
            candidateFeedback.Specialization = specialization;
            candidateFeedback.SuggestedConsultingRole = suggestedConsultingRole;
            candidateFeedback.SuggestedExperienceLevel = suggestedExperienceLevel;
            candidateFeedback.Hire = hire;
            return candidateFeedback;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CandidateId
        {
            get
            {
                return _CandidateId;
            }
            set
            {
                OnCandidateIdChanging(value);
                ReportPropertyChanging("CandidateId");
                _CandidateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateId");
                OnCandidateIdChanged();
            }
        }
        private global::System.Int32 _CandidateId;
        partial void OnCandidateIdChanging(global::System.Int32 value);
        partial void OnCandidateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InterviewerId
        {
            get
            {
                return _InterviewerId;
            }
            set
            {
                OnInterviewerIdChanging(value);
                ReportPropertyChanging("InterviewerId");
                _InterviewerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterviewerId");
                OnInterviewerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _InterviewerId;
        partial void OnInterviewerIdChanging(Nullable<global::System.Int32> value);
        partial void OnInterviewerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Specialization
        {
            get
            {
                return _Specialization;
            }
            set
            {
                OnSpecializationChanging(value);
                ReportPropertyChanging("Specialization");
                _Specialization = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Specialization");
                OnSpecializationChanged();
            }
        }
        private global::System.Int32 _Specialization;
        partial void OnSpecializationChanging(global::System.Int32 value);
        partial void OnSpecializationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SuggestedConsultingRole
        {
            get
            {
                return _SuggestedConsultingRole;
            }
            set
            {
                OnSuggestedConsultingRoleChanging(value);
                ReportPropertyChanging("SuggestedConsultingRole");
                _SuggestedConsultingRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuggestedConsultingRole");
                OnSuggestedConsultingRoleChanged();
            }
        }
        private global::System.Int32 _SuggestedConsultingRole;
        partial void OnSuggestedConsultingRoleChanging(global::System.Int32 value);
        partial void OnSuggestedConsultingRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SuggestedExperienceLevel
        {
            get
            {
                return _SuggestedExperienceLevel;
            }
            set
            {
                OnSuggestedExperienceLevelChanging(value);
                ReportPropertyChanging("SuggestedExperienceLevel");
                _SuggestedExperienceLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuggestedExperienceLevel");
                OnSuggestedExperienceLevelChanged();
            }
        }
        private global::System.Int32 _SuggestedExperienceLevel;
        partial void OnSuggestedExperienceLevelChanging(global::System.Int32 value);
        partial void OnSuggestedExperienceLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Hire
        {
            get
            {
                return _Hire;
            }
            set
            {
                OnHireChanging(value);
                ReportPropertyChanging("Hire");
                _Hire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hire");
                OnHireChanged();
            }
        }
        private global::System.Boolean _Hire;
        partial void OnHireChanging(global::System.Boolean value);
        partial void OnHireChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Candidate", "Candidate")]
        public Candidate Candidate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "Candidate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "Candidate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candidate> CandidateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Candidate", "Candidate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback1")]
        public CandidateFeedback CandidateFeedback1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CandidateFeedback> CandidateFeedback1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback")]
        public CandidateFeedback CandidateFeedback2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CandidateFeedback> CandidateFeedback2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_CandidateFeedback", "CandidateFeedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Interviewer", "Interviewer")]
        public Interviewer Interviewer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "Interviewer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "Interviewer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Interviewer> InterviewerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "Interviewer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "Interviewer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="Competency")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Competency : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Competency object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="competencyArea">Initial value of the CompetencyArea property.</param>
        /// <param name="reviewCategory">Initial value of the ReviewCategory property.</param>
        /// <param name="competencyDescription">Initial value of the CompetencyDescription property.</param>
        public static Competency CreateCompetency(global::System.Int32 id, global::System.Int32 competencyArea, global::System.String reviewCategory, global::System.String competencyDescription)
        {
            Competency competency = new Competency();
            competency.Id = id;
            competency.CompetencyArea = competencyArea;
            competency.ReviewCategory = reviewCategory;
            competency.CompetencyDescription = competencyDescription;
            return competency;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompetencyArea
        {
            get
            {
                return _CompetencyArea;
            }
            set
            {
                OnCompetencyAreaChanging(value);
                ReportPropertyChanging("CompetencyArea");
                _CompetencyArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetencyArea");
                OnCompetencyAreaChanged();
            }
        }
        private global::System.Int32 _CompetencyArea;
        partial void OnCompetencyAreaChanging(global::System.Int32 value);
        partial void OnCompetencyAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReviewCategory
        {
            get
            {
                return _ReviewCategory;
            }
            set
            {
                OnReviewCategoryChanging(value);
                ReportPropertyChanging("ReviewCategory");
                _ReviewCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReviewCategory");
                OnReviewCategoryChanged();
            }
        }
        private global::System.String _ReviewCategory;
        partial void OnReviewCategoryChanging(global::System.String value);
        partial void OnReviewCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompetencyDescription
        {
            get
            {
                return _CompetencyDescription;
            }
            set
            {
                OnCompetencyDescriptionChanging(value);
                ReportPropertyChanging("CompetencyDescription");
                _CompetencyDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompetencyDescription");
                OnCompetencyDescriptionChanged();
            }
        }
        private global::System.String _CompetencyDescription;
        partial void OnCompetencyDescriptionChanging(global::System.String value);
        partial void OnCompetencyDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Competency", "CompetencyFeedback")]
        public EntityCollection<CompetencyFeedback> CompetencyFeedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "CompetencyFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "CompetencyFeedback", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="CompetencyFeedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompetencyFeedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompetencyFeedback object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="candidateId">Initial value of the CandidateId property.</param>
        /// <param name="competencyId">Initial value of the CompetencyId property.</param>
        /// <param name="note">Initial value of the Note property.</param>
        public static CompetencyFeedback CreateCompetencyFeedback(global::System.Int32 id, global::System.Int32 candidateId, global::System.Int32 competencyId, global::System.String note)
        {
            CompetencyFeedback competencyFeedback = new CompetencyFeedback();
            competencyFeedback.Id = id;
            competencyFeedback.CandidateId = candidateId;
            competencyFeedback.CompetencyId = competencyId;
            competencyFeedback.Note = note;
            return competencyFeedback;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CandidateId
        {
            get
            {
                return _CandidateId;
            }
            set
            {
                OnCandidateIdChanging(value);
                ReportPropertyChanging("CandidateId");
                _CandidateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateId");
                OnCandidateIdChanged();
            }
        }
        private global::System.Int32 _CandidateId;
        partial void OnCandidateIdChanging(global::System.Int32 value);
        partial void OnCandidateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InterviewerId
        {
            get
            {
                return _InterviewerId;
            }
            set
            {
                OnInterviewerIdChanging(value);
                ReportPropertyChanging("InterviewerId");
                _InterviewerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterviewerId");
                OnInterviewerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _InterviewerId;
        partial void OnInterviewerIdChanging(Nullable<global::System.Int32> value);
        partial void OnInterviewerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompetencyId
        {
            get
            {
                return _CompetencyId;
            }
            set
            {
                OnCompetencyIdChanging(value);
                ReportPropertyChanging("CompetencyId");
                _CompetencyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetencyId");
                OnCompetencyIdChanged();
            }
        }
        private global::System.Int32 _CompetencyId;
        partial void OnCompetencyIdChanging(global::System.Int32 value);
        partial void OnCompetencyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompetencyLevel
        {
            get
            {
                return _CompetencyLevel;
            }
            set
            {
                OnCompetencyLevelChanging(value);
                ReportPropertyChanging("CompetencyLevel");
                _CompetencyLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetencyLevel");
                OnCompetencyLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _CompetencyLevel;
        partial void OnCompetencyLevelChanging(Nullable<global::System.Int32> value);
        partial void OnCompetencyLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Candidate", "Candidate")]
        public Candidate Candidate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "Candidate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "Candidate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candidate> CandidateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Candidate", "Candidate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Competency", "Competency")]
        public Competency Competency
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competency>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "Competency").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competency>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "Competency").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Competency> CompetencyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competency>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "Competency");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Competency>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Competency", "Competency", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Interviewer", "Interviewer")]
        public Interviewer Interviewer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "Interviewer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "Interviewer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Interviewer> InterviewerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "Interviewer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "Interviewer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="Interviewer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Interviewer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Interviewer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        public static Interviewer CreateInterviewer(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.String emailAddress)
        {
            Interviewer interviewer = new Interviewer();
            interviewer.Id = id;
            interviewer.FirstName = firstName;
            interviewer.LastName = lastName;
            interviewer.EmailAddress = emailAddress;
            return interviewer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CandidateFeedback_Interviewer", "CandidateFeedback")]
        public EntityCollection<CandidateFeedback> CandidateFeedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "CandidateFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CandidateFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CandidateFeedback_Interviewer", "CandidateFeedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_CompetencyFeedback_Interviewer", "CompetencyFeedback")]
        public EntityCollection<CompetencyFeedback> CompetencyFeedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "CompetencyFeedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CompetencyFeedback>("Slalom.CustomAppDev.RecruitingManagerModel.FK_CompetencyFeedback_Interviewer", "CompetencyFeedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Interviewer", "InterviewSession")]
        public EntityCollection<InterviewSession> InterviewSessions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InterviewSession>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "InterviewSession");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InterviewSession>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "InterviewSession", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Slalom.CustomAppDev.RecruitingManagerModel", Name="InterviewSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InterviewSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InterviewSession object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="interviewerId">Initial value of the InterviewerId property.</param>
        /// <param name="candidateId">Initial value of the CandidateId property.</param>
        /// <param name="started">Initial value of the Started property.</param>
        public static InterviewSession CreateInterviewSession(global::System.Int32 id, global::System.Int32 interviewerId, global::System.Int32 candidateId, global::System.DateTime started)
        {
            InterviewSession interviewSession = new InterviewSession();
            interviewSession.Id = id;
            interviewSession.InterviewerId = interviewerId;
            interviewSession.CandidateId = candidateId;
            interviewSession.Started = started;
            return interviewSession;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InterviewerId
        {
            get
            {
                return _InterviewerId;
            }
            set
            {
                OnInterviewerIdChanging(value);
                ReportPropertyChanging("InterviewerId");
                _InterviewerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterviewerId");
                OnInterviewerIdChanged();
            }
        }
        private global::System.Int32 _InterviewerId;
        partial void OnInterviewerIdChanging(global::System.Int32 value);
        partial void OnInterviewerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CandidateId
        {
            get
            {
                return _CandidateId;
            }
            set
            {
                OnCandidateIdChanging(value);
                ReportPropertyChanging("CandidateId");
                _CandidateId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CandidateId");
                OnCandidateIdChanged();
            }
        }
        private global::System.Int32 _CandidateId;
        partial void OnCandidateIdChanging(global::System.Int32 value);
        partial void OnCandidateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Started
        {
            get
            {
                return _Started;
            }
            set
            {
                OnStartedChanging(value);
                ReportPropertyChanging("Started");
                _Started = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Started");
                OnStartedChanged();
            }
        }
        private global::System.DateTime _Started;
        partial void OnStartedChanging(global::System.DateTime value);
        partial void OnStartedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Completed;
        partial void OnCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnCompletedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Candidate", "Candidate")]
        public Candidate Candidate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "Candidate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "Candidate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candidate> CandidateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "Candidate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candidate>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Candidate", "Candidate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Slalom.CustomAppDev.RecruitingManagerModel", "FK_InterviewSession_Interviewer", "Interviewer")]
        public Interviewer Interviewer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "Interviewer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "Interviewer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Interviewer> InterviewerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "Interviewer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Interviewer>("Slalom.CustomAppDev.RecruitingManagerModel.FK_InterviewSession_Interviewer", "Interviewer", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
