insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Java','Inheritance, Interfaces, Exception handling, Futures')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Core J2EE','Database Interaction:                                JDBC, JPA, JTA')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Core J2EE','Web Apps (Server Side):  JSP, JSF')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Servers','Tomcat, JBoss, Glassfish, WebLogic, Websphere')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Server OS','Linux, Unix')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','SQL','PL-SQL, T-SQL, other')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Databases','Oracle, MySQL, other')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','Web Services:                              JAX-WS, JAX-RS')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','ORMs: Hibernate or other')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','Web Apps / Client Side: Javascript, jQuery, HTML5, CSS3')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','Messaging and Integration: JMS, Mule and other ESBs (e.g. ServiceMix, Camel, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','Dependency Injection and Mock Frameworks:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('1','Other','Spring, etc.')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','C#','Inheritance, Interfaces, Exception handling, LINQ, Lambdas, Generics, Value vs. Reference types')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Core .NET','Database Interaction:                                ADO.NET')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Core .NET','Web Apps (Server Side): ')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Core .NET','IIS, ASP.NET, Web Forms, ASP.NET MVC')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Core .NET','Windows Apps:                         WPF, XAML, Silverlight, Windows Metro')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Azure','Any skills (e.g. Web/Worker roles, Service Bus, Azure Storage, Azure SQL)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Server OS','Windows Server 2008 and higher, IIS')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','SQL','T-SQL')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Databases','SQL Server')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Web Services:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','WCF, Web API')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','ORMs:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Entity Framework, nHibernate, or other')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Web Apps / Client Side: Javascript, jQuery, HTML5, CSS3, Knockout-JS')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Messaging and Integration: MSMQ, Biztalk')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Dependency Injection and Mock Frameworks:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','Spring.NET, Moq, MEF, etc.')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('2','Other','App Fabric, Windows Workflow (WF)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','AWS','EC2, S3, CloudFront, Beanstalk, DynamoDB, SQS, SWF, etc.')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','Concepts:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','When to use,')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','Understanding of key styles (e.g. key/value, document, object, graph, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','Actual Experience:')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','MongoDB (document), Neo4J (graph), Riak (distributed p2p), etc.')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','NoSQL Databases','PHP, Perl, Python, Ruby on Rails')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','Mobile','iOS / Objective-C')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('3','Mobile','Android / Java')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Design Patterns','Understanding of GoF patterns')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Design Patterns','Understanding of                   Fowler Signature Series               (i.e. Patterns of Enterprise Application Architecture, Enterprise Integration Patterns, Service Design Patterns)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Code Craftsmanship','Understanding of SOLID principles, Object-Oriented design, Domain Driven Design (DDD), Relational theory (up to 3rd Normal Form), asynchronous programming (e.g. multi-threading and other)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Architecture','Ability to define and manage non-functional requirements (e.g. performance, availability and fault-tolerance, interoperability, security, auditing/logging, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Architecture','Ability to devise appropriate Layering and tiering strategies')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Architecture','Understanding of tactical and strategic planning considerations (e.g. evaluating client constraints and goals, team skills, technology trends, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Architecture','Ability to articulate technology road-maps')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Quality','Unit Testing and actual experience (e.g. with JUNit, NUnit, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('4','Software Quality','Continuous Integration (e.g. Nightly Builds, Cruise Control, TFS Build Server, etc.)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Agile','Scrum Facilitation,                Scrum Master experience')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Agile','Release Planning')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Agile','Backlog management')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Agile','Retrospectives (ability to facilitate or experience as a participant)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Estimating','Work-effort estimation')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Estimating','Schedule estimation')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Project Monitoring and Reporting','Project Velocity')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Project Monitoring and Reporting','Backlog burn-down and presentation')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Project Monitoring and Reporting','Risk management (i.e. identification and mitigation)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('5','Influence and Authority','What was their most significant role, and what was their level of influence or authority?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('6','Requirements Definition','Ability to elicit customer requirements and develop a deep understanding of their needs')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('6','Articulation of Courses of Action','Ability to suggest courses of action (influencing skills)')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('6','Conflict Resolution','Did they provide an example of how they resolved issues where 2 or more parties had differing points of views or competing agendas? Please describe.')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Interpersonal style (Where do they appear on these continuums? )','-  Confidence vs. Humility')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Interpersonal style (Where do they appear on these continuums? )','-  Assertive vs. Passive')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Interpersonal style (Where do they appear on these continuums? )','-  Serious vs. Light-hearted')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Interpersonal style','Do you think they know how/when to turn each style up or down based on the situation?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Interpersonal style','Are they friendly, likeable, personable?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','How well do they answer questions?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','Are they credible?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','Do they ramble on and provide actual answers?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','Are their answers vague/confusing or clear and concise?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','Do they have proven/demonstrated experience writing (e.g. blogs, magazines, etc.) or speaking (e.g. user-groups, conferences)?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Ability to articulate','Could they facilitate a group meeting?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Empathy','Can they “read” others, adapt appropriately, and bond with them?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Team Attitude','Do they seem to have the ability to balance “personal achievement/career goals” vs. “team/company goals”?')
insert into Competency (CompetencyArea, ReviewCategory, CompetencyDescription) values ('7','Team Attitude','Do they seem to understand how to collaborate on teams? (I.e. give and take, quid-pro-quo, how to work through problems/debate issues respectfully, work for consensus, etc.)?')
